spring:
  datasource:
    url: jdbc:mysql://47.106.254.86/Authentication?characterEncoding=utf8&useSSL=true
    username: lumnca
    password: chuan868
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  mail:
    host: smtp.qq.com
    port: 587
    username: 724119519@qq.com
    password: ucfpbggwfeqkbbjh
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
      debug: true
server:
  port: 81
